export const userimages = [
    require('../assets/images/1.png'),
    require('../assets/images/2.png'),
    require('../assets/images/3.png'),
    require('../assets/images/4.png'),
    require('../assets/images/5.png'),
    require('../assets/images/6.png'),
    require('../assets/images/7.png'),
]
const imgs = [
    require('../assets/arrow.png'),
    require('../assets/logo.png'),
    require('../assets/scene1/bg.jpg'),
    require('../assets/scene1/button.png'),
    require('../assets/scene1/letter.png'),
    require('../assets/scene2/bg.jpg'),
    require('../assets/scene2/letter.png'),
    require('../assets/scene3/bg.jpg'),
    require('../assets/scene3/btn-bg_01.png'),
    require('../assets/scene3/images/demo.jpg'),
    require('../assets/scene3/letter.png'),
    require('../assets/scene3/pic-bg.png'),
    require('../assets/scene3/pic-bg_03.png'),
    require('../assets/scene3/pic-ping.png'),
    require('../assets/scene3/pinig_03.png'),
    require('../assets/scene3/spliter_03.png'),
    require('../assets/scene3/title-bg_03.png'),
    require('../assets/scene3/title_03.png'),
    require('../assets/scene4/bg.jpg'),
    require('../assets/scene4/button.png'),
    require('../assets/scene4/greet-bg.png'),
    require('../assets/scene4/letter.png'),
    require('../assets/scene4/pic.png'),
    require('../assets/scene4/spliterpng.png'),
    require('../assets/scene4/title.png'),
    ...userimages,
]

export default imgs;
